server:
  port: 8080

spring:
  dubbo:
    application:
      name: provider
    server: true
    registry:
      address: zookeeper://111.231.65.247:2181
    protocol:
      name: dubbo
      port: 20880