server:
  port: 8081

spring:
  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://111.231.65.247:2181
    protocol:
      name: dubbo
      port: 20880
    consumer:
      check: false
    reference:
      loadbalance: roundrobin
